name: Deploy .NET Core App

on:
  push:
    branches: [ "main" ] # Triggers on push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build SeizureTrackerService/SeizureTrackerService.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish SeizureTrackerService/SeizureTrackerService.csproj -c Release -o ${{env.DOTNET_ROOT}}/appTemp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'seizuretracker-api-stg' # Your exact App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/myapp
